# general settings
name: train_lcdp
model_type: FTModel2
scale: 1
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: LCDP
    type: PairedResizeImageDataset
    dataroot_gt: XXX
    dataroot_lq: XXX
    filename_tmpl: "{}"
    io_backend:
      type: disk

    gt_size: 768
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: LCDP
    type: PairedResizeImageDataset
    dataroot_gt: XXX
    dataroot_lq: XXX
    io_backend:
      type: disk

# network structures
network_g:
  type: CoNet
  n_vertices_3d: 17
  input_resolution: 256

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000]
    restart_weights: [1]
    eta_min: !!float 1e-6

  total_iter: 100000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 10.0
    reduction: mean
  ssim_opt:
    type: SSIMLoss
    loss_weight: 5.0
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      "conv1_2": 0.1
      "conv2_2": 0.1
      "conv3_4": 1
      "conv4_4": 1
      "conv5_4": 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 0.1
    style_weight: 0
    range_norm: false
    criterion: l1

# validation settings
val:
  val_freq: !!float 10e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 10e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
